In [1]:
import tensorflow as tf
import numpy as np

In [2]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1])
predictions

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 0.05252838,  0.4368809 , -0.20730308, -0.20361942,  0.27402174,
        -0.38216063, -0.23386705, -0.28138256,  0.49822944, -0.69218194]],
      dtype=float32)>

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.10623813, 0.15602802, 0.08192888, 0.08223124, 0.1325787 ,
        0.06878558, 0.07978118, 0.07607899, 0.16589983, 0.0504495 ]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1],predictions).numpy()

2.6767612

In [11]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [12]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 1ms/step - loss: 0.4817 - accuracy: 0.8584
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1532 - accuracy: 0.9542
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1143 - accuracy: 0.9652
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0840 - accuracy: 0.9747
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0720 - accuracy: 0.9776


In [13]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0804 - accuracy: 0.9742


[0.0803566500544548, 0.9742000102996826]

In [15]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.9545552e-08, 1.5751368e-09, 2.0676697e-04, 2.0874829e-04,
        1.8720443e-10, 3.5783498e-07, 1.2907069e-13, 9.9958152e-01,
        1.1350389e-06, 1.3898714e-06],
       [1.7645490e-08, 8.7451204e-05, 9.9953234e-01, 3.7919552e-04,
        1.8982368e-12, 3.9036237e-08, 1.2398785e-07, 9.3515344e-14,
        9.0621819e-07, 3.9302125e-12],
       [2.6910845e-07, 9.9916458e-01, 3.5773113e-04, 1.1950948e-05,
        2.1039938e-05, 3.6386582e-06, 7.3654060e-06, 3.7767185e-04,
        5.5080574e-05, 7.1293761e-07],
       [9.9183428e-01, 1.1614861e-08, 8.0313478e-03, 5.4507276e-05,
        1.3202244e-06, 3.8692309e-05, 2.9418325e-05, 4.9895457e-06,
        1.6948098e-07, 5.4364950e-06],
       [2.4054645e-05, 2.0333584e-08, 3.3520053e-05, 1.7705390e-06,
        9.6838224e-01, 2.0210080e-05, 4.1621461e-06, 2.8400539e-04,
        2.8495331e-06, 3.1247191e-02]], dtype=float32)>